language: cpp

os:
  - linux

branches:
  only:
    - master

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8

sudo:
  - false

before_script:
  - cd server-plugin

script:
  - make clean
  - make debug
  - make release
