language: cpp
compiler:
  - g++
os: linux
sudo: required
dist: trusty
branches:
  only:
  - master
  - /^v4-r\d+*$/
before_install:
  - sudo rm /etc/apt/sources.list.d/google-chrome.list
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y build-essential cppcheck g++-4.8 g++-multilib linux-libc-dev libc6-dev-i386 lib32z1-dev lib32stdc++6
before_script:
  - git fetch --tags
  - git tag
  - cd scripts
  - python version.py
  - cd ../server-plugin
  - sh ../scripts/make-protobuf.sh
script:
  - make debug CXX=g++-4.8 -j 3
  - make release CXX=g++-4.8 -j 3
  - cd ../scripts
  - python validate-libc-version.py 2.4.0 3.4.16 ../Builds/Debug/addons/NoCheatZ/nocheatzX.so ../Builds/Release/addons/NoCheatZ/nocheatzX.so
before_deploy:
  - cd ..
  - sh scripts/ci-before-deploy.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: oU1lQi1TA/Kaa/aIKuCe/2VJxlVTnu1kZyO4nLkwaVArZpJwqdjgm++66mIPkvi4A62MolCUErI7rcTEGKXDjUo7rByTp9dVCiTxFbrEJiLWq5V5mEwFEqq5W1vl+iI0e0Lgr+jqiy9n6SNlQ7r5jbypZA3tmrWQg7x04UILPwa77d9G37/HoXL5rBcLQdFx3J9pNEZLHGyrxKusOJfZ5gBoWZRlz5uX4z5CLvUPPF+uZCvB5tp31OLSa8kEKtTi5D1SRmzz8/ofGIW3so9wSILTz0MKqS1Wsk5VSG54a1Sg3RYB13PjrlhIqQP2qTCA+2N7aRzPogIjgywPeg7h/BZFdEdnZBZioDGw2oaJZxxq4tG/csgsqmyICu/6zJNU5A8hvKBTtKKrDdoqH4Qwh2xU6Eni9ZBHmznhpo5noiGzwE63bsBc8TaWTv5C542hIy79BbQFIUbO/9XhHUc9Tha3uGWbWKmPv82IrPBrbdTWdr1Iit40Sb7z5tJ1TOaiQ+8rop/TvGiTa8Mg2hEtBtjJRRw6Tg3Z0P85y1cWbd+lz5asqey30HdGKTg/pqSkWI9GwsZupdm5ZcPpwA0VaxFKTaxvRctEu50B16O11n16HnGXvkCS913MJePhm+jo2I+Z2T0m5P486UwD+jywJ82kU8rnqYWhJVcjvPjGGaA=
  file_glob: true
  file: Builds/out/*.tar.gz
  on:
    tags: true
    all_branches: true
