version: r{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - appveyor-test
  - dev2
  - master
max_jobs: 1
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Win32
clone_folder: c:\github\NoCheatZ-4
install:
- ps: >-
    git submodule update --init --recursive

    cd c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    Start-FileDownload "https://github.com/google/protobuf/archive/v2.5.0.zip"

    Expand-Archive v2.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    del v2.5.0.zip

    cd protobuf-2.5.0\

    Start-FileDownload "https://github.com/google/googletest/archive/release-1.5.0.zip"

    Expand-Archive release-1.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\protobuf-2.5.0\

    del release-1.5.0.zip

    Rename-Item googletest-release-1.5.0 gtest
cache: c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\protobuf-2.5.0
build:
  project: nocheatz.sln
  parallel: true
  verbosity: minimal