version: v4-r{build}
pull_requests:
  do_not_increment_build_number: true
max_jobs: 2
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Win32
clone_folder: c:\github\NoCheatZ-4
install:
- ps: >-
    git submodule update --init --recursive

    cd c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    Start-FileDownload "https://github.com/google/protobuf/archive/v2.5.0.zip"

    Expand-Archive v2.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    del v2.5.0.zip

    cd protobuf-2.5.0\

    Start-FileDownload "https://github.com/google/googletest/archive/release-1.5.0.zip"

    Expand-Archive release-1.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\protobuf-2.5.0\

    del release-1.5.0.zip

    Rename-Item googletest-release-1.5.0 gtest
build:
  project: nocheatz.sln
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    $ErrorActionPreference = 'SilentlyContinue'

    $p0 = $env:configuration + "\*"

    $p3 = $env:configuration + "-Windows.zip"

    $p1 = "out\" + $p3

    $p2 = "Builds\" + $p1

    cd c:\github\NoCheatZ-4\Builds

    Get-ChildItem -Include *.exp | Remove-Item -recurse

    Get-ChildItem -Include *.ilk | Remove-Item -recurse

    Get-ChildItem -Include *.lib | Remove-Item -recurse

    Get-ChildItem -Include *.bsc | Remove-Item -recurse

    Get-ChildItem -Include .gitignore | Remove-Item -recurse

    New-Item -ItemType directory -Path out

    Compress-Archive -Path $p0 -DestinationPath $p1

    cd ..

    Push-AppveyorArtifact $p2 -FileName $p3 -DeploymentName deploy-out
deploy:
- provider: GitHub
  tag: $(version)
  release: NoCheatZ $(version)
  auth_token:
    secure: cmeI5Mwc+kiqp/KVpsM++TVOdsmMhb1jIAnW9oeV27mxuQpiHD5uu1zlHCD9ttLA
  artifact: deploy-out
