version: r{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
max_jobs: 2
image: Visual Studio 2017
configuration:
- Debug
- Release
artifacts:
  - path: Builds\out\$(configuration)-Windows.zip
    name: ncz-$(APPVEYOR_REPO_TAG_NAME)-$(configuration)-Windows.zip
    type: zip
platform: Win32
clone_folder: c:\github\NoCheatZ-4
install:
- ps: >-
    git submodule update --init --recursive

    cd c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    Start-FileDownload "https://github.com/google/protobuf/archive/v2.5.0.zip"

    Expand-Archive v2.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    del v2.5.0.zip

    cd protobuf-2.5.0\

    Start-FileDownload "https://github.com/google/googletest/archive/release-1.5.0.zip"

    Expand-Archive release-1.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\protobuf-2.5.0\

    del release-1.5.0.zip

    Rename-Item googletest-release-1.5.0 gtest
build:
  project: nocheatz.sln
  parallel: true
  verbosity: minimal
 
after_build:
- ps: >-
    $ErrorActionPreference = 'SilentlyContinue'

    $p0 = $env:configuration + "\*"

    $p1 = "out\" + $env:configuration + "-Windows.zip"

    $p2 = "Builds\" + $p1

    cd ..\Builds

    Get-ChildItem -Include *.exp | Remove-Item -recurse

    Get-ChildItem -Include *.ilk | Remove-Item -recurse

    Get-ChildItem -Include *.lib | Remove-Item -recurse

    Get-ChildItem -Include *.bsc | Remove-Item -recurse

    Get-ChildItem -Include .gitignore | Remove-Item -recurse

    New-Item -ItemType directory -Path out

    Compress-Archive -Path $p0 -DestinationPath $p1

    cd ..

    Push-AppveyorArtifact $p2
deploy:
  release: NoCheatZ-v4-r$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: Fq0z0kE14rIeOVfo5RcAEPMO57YOsEPigKUGbgV7ZiwfFu25w7Qi0ngdhyBYl09k
  artifact: Builds\out\*
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
