version: r{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - appveyor-test
max_jobs: 1
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Win32
clone_folder: c:\github\NoCheatZ-4
install:
- ps: scripts\appveyor-install.ps1
	
build:
  project: nocheatz.sln
  parallel: true
  verbosity: minimal